apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-registry
  namespace: "spinnaker"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-registry
    spec:
      containers:
      - name: spinnaker-registry
        image: registry:2.4.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry/
          name: registry-img
      volumes:
      - name: registry-img
        persistentVolumeClaim:
          claimName: myclaim

